- name: Deploy to EC2
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: |
      ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd /home/ubuntu/Api/Aws
      git pull origin main
      npm install
      pm2 restart Api
